version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/masumi_agent
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MASUMI_AGENT_ID=${MASUMI_AGENT_ID}
      - MASUMI_API_KEY=${MASUMI_API_KEY}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=masumi_agent
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 